name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - uses: actions/checkout@v2
      - run: make -B .env env=local
      - run: go mod download
      - run: make deps
      - run: ./scripts/migrate.sh up
      - run: make test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make -B .env env=docker
      - run: docker-compose build app
